openapi: 3.0.1
info:
  title: Car Fleet Service API
  description: Car Fleet Service API
  version: 1.0.0
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://thinkpad01:8030
tags:
  - name: car
    description: Operations about Car
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io

paths:
  /cars:
    get:
      tags:
        - car
      operationId: getCars
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Car"

components:
  schemas:
    Car:
      required:
        - publicId
      type: object
      properties:
        publicId:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
